# Current keybinds
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-a
bind C-a send-prefix

set -g mouse on

bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R

set-option -g status-position bottom 
set -g status-style "fg=black bg=default"

set -g pane-border-style fg=default,bg=default
set -g pane-active-border-style fg=default,bg=default

set -g window-style 'bg=default'
set -g window-active-style 'bg=default'

# New settings
set-option -sa terminal-overrides ",xterm*:Tc"
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Plugins and settings
set -g @catppuccin_flavour 'mocha'
set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_path_format relative
set -g @tokyo-night-tmux_window_id_style dsquare
set -g @tokyo-night-tmux_show_git 0

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Keybindings for vi-mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Split windows keeping the current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Plugins or settings no longer used
# battery
# set -g @plugin 'tmux-plugins/tmux-battery'

# catppuccin settings
# set -g @plugin 'catppuccin/tmux'
