version = 3
final_space = true

[secondary_prompt]
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '❯❯'
  background = '#29315A'
  type = 'text'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}#7FD5EA{{end}}']

[transient_prompt]
  template = "\n❯ "
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}#7FD5EA{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ' '
    template = ' {{ .Path }}'
    foreground = '#3EC669'
    background = '#29315A'
    type = 'path'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .HEAD }}'
    foreground = '#43CCEA'
    background = '#29315A'
    type = 'git'

    [blocks.segments.properties]
      branch_icon = ''

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}'
    foreground = '#E4F34A'
    background = '#29315A'
    type = 'python'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .UserName }}'
    foreground = '#E64747'
    background = '#29315A'
    type = 'session'

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ' '
    trailing_diamond = ''
    template = '{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}'
    foreground = '#9B6BDF'
    background = '#29315A'
    type = 'battery'
    foreground_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = '⇡ '
      discharging_icon = '⇣ '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ' '
    template = '{{ .FormattedMs }}'
    foreground = '#AEA4BF'
    background = '#29315A'
    type = 'executiontime'

    [blocks.segments.properties]
      style = 'austin'
      threshold = 150

  [[blocks.segments]]
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '❯'
    background = '#29315A'
    type = 'text'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}#7FD5EA{{end}}']
