#!/usr/bin/env zsh

SKETCHYBAR_CONFIG="${SKETCHYBAR_CONFIG:-$HOME/.config/sketchybar}"

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$SKETCHYBAR_CONFIG/plugins"
SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"


sketchybar --bar \
    height=32 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=25 \
    padding_right=21 \
    notch_width=175 \
    display=main

# Alternative background colors
# label.color=0xffffffff
# background.color=0x9924273a

sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item cover e \
    --set cover \
    background.color=0x00000000 \
    label.drawing=off \
    padding_left=-10 \
    --add item spotify.prev e \
    --set spotify.prev \
    icon=󰒮 \
    icon.color=0xffcad3f5 \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:16.0" \
    icon.padding_left=6 \
    icon.padding_right=2 \
    label.drawing=off \
    background.drawing=off \
    click_script="osascript -e 'tell application \"Spotify\" to previous track'" \
    --add item spotify.play e \
    --set spotify.play \
    icon= \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:18.0" \
    icon.padding_left=2 \
    icon.padding_right=2 \
    label.drawing=off \
    background.drawing=off \
    click_script="osascript -e 'tell application \"Spotify\" to playpause'" \
    --add item spotify.next e \
    --set spotify.next \
    icon=󰒭 \
    icon.color=0xffcad3f5 \
    icon.y_offset=1 \
    icon.font="$FONT_FACE:Bold:16.0" \
    icon.padding_left=2 \
    icon.padding_right=6 \
    label.drawing=off \
    background.drawing=off \
    click_script="osascript -e 'tell application \"Spotify\" to next track'" \
    --add item spotify.title e \
    --set spotify.title \
    icon.drawing=off \
    label.drawing=off \
    label.padding_left=3 \
    background.drawing=off \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify.title spotify_change

sketchybar --add bracket spotify.container \
    spotify.title \
    spotify.prev \
    spotify.play \
    spotify.next \
    --set spotify.container \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.height=26 \
    background.padding_left=5 \
    background.padding_right=5


sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

front_app=(
  label.font="SF Pro:Black:11.0"
  label.drawing=off
  icon.background.drawing=on
  display=active
  script="$PLUGIN_DIR/front_app.sh"
  click_script="open -a 'Mission Control'"
)

sketchybar --add item front_app left \
    --set front_app "${front_app[@]}" \
    --subscribe front_app front_app_switched

sketchybar --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-7 \
    icon= \
    icon.color=0xff353a61 \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=off

sketchybar --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=6 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=on

sketchybar --add item weather q \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:15.0" \
    label.drawing=on \
    label="Loading..." \
    update_freq=1800 \
    script="$PLUGIN_DIR/weather.sh" \
    --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=on \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change

sketchybar --update
sketchybar --trigger space_change
