#!/bin/bash

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=32 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=23 \
    padding_right=23 \
    notch_width=175 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a

sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="$FONT_FACE:Medium:12.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item cover e \
    --set cover background.color=0x00000000 \
             label.drawing=no \
             padding_left=-10 \
    --add item spotify e \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    icon.padding_left=5 \
    icon.font="$FONT_FACE:Bold:20.0" \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked


# sketchybar --add event spotify_change $SPOTIFY_EVENT \
#     --add item cover e \
#     --set cover background.color=0x00000000 label.drawing=no \
#     --add item spotify e \
#     --set spotify \
#     icon.y_offset=1 \
#     icon.padding_left=5 \
#     icon.font="$FONT_FACE:Bold:20.0" \
#     label.drawing=off \
#     label.padding_left=3 \
#     script="$PLUGIN_DIR/spotify.sh" \
#     --subscribe spotify spotify_change mouse.clicked


sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.color=0xff24273a \
    label.drawing=off \
    script="$PLUGIN_SHARED_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

front_app=(
  label.font="SF Pro:Black:11.0"
  label.drawing=off
  icon.background.drawing=on
  display=active
  script="$HOME/dotfiles/.config/sketchybar/plugins/front_app.sh"
  click_script="open -a 'Mission Control'"
)

sketchybar --add item front_app left \
    --set front_app "${front_app[@]}" \
    --subscribe front_app front_app_switched

sketchybar --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-7 \
    icon= \
    icon.color=0xff353a61\
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \

sketchybar --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=6 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:12.0" \
    label.drawing=yes



# sketchybar --add item weather.moon q \
#     --set weather.moon \
#     background.color=0x667dc4e4 \
#     background.padding_right=-1 \
#     icon.color=0xff181926 \
#     icon.font="$FONT_FACE:Bold:22.0" \
#     icon.padding_left=4 \
#     icon.padding_right=3 \
#     label.drawing=off \
#     --subscribe weather.moon mouse.clicked

sketchybar --add item weather q \
  --set weather \
  icon= \
  icon.color=0xfff5bde6 \
  icon.font="$FONT_FACE:Bold:15.0" \
  label.drawing=yes \
  label="Loading..." \
  update_freq=1800 \
  script="$PLUGIN_SHARED_DIR/weather.sh" \
  --subscribe weather system_woke

sketchybar --add bracket front_app_bracket \
  front_app \
  front_app.separator \
  front_app.name \
  --subscribe front_app front_app_switched

sketchybar --add item clock right \
  --set clock \
  icon=󰃰 \
  icon.color=0xffed8796 \
  update_freq=10 \
  script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar --add item battery right \
  --set battery \
  update_freq=20 \
  script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
  --set volume \
  icon.color=0xff8aadf4 \
  label.drawing=true \
  script="$PLUGIN_SHARED_DIR/volume.sh" \
  --subscribe volume volume_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
